### ISSUE TITLE
Add more server commands

### ISSUE THREAD

**Issue by roseduan** [rosedblabs/rosedb#146]
rosedb is starting to support `redis` protocol, so you can add the commands compatible with redis protocol:
- find variable `supportedCommands` in `cmd/cli.go`, which lists all supported commands and its handler function
- find a method in rosedb not listed here
- add the command and its handler function

**Comment by gozeloglu** [comment]
Hi @roseduan. Do you mean [this part](https://redis.io/commands/?group=server)?

**Comment by roseduan** [comment]
No
Just add those commands(already in rosedb) in `supportedCommands` in `cmd/cli.go`, aims to support redis protocol.

**Comment by gozeloglu** [comment]
Ok. I'll try to do something as soon as possible.

**Comment by roseduan** [comment]
> Ok. I'll try to do something as soon as possible.

That will be great, thanks for your recent work on this project!

**Comment by gozeloglu** [comment]
@roseduan You can close this issue.

**Comment by roseduan** [comment]
maybe there are more commands later @gozeloglu

**Comment by azhsmesos** [comment]
do we Need to implement Stream？  I would like to contribute an implementation of Stream to RoseDB
