### ISSUE TITLE
Join Community

### ISSUE THREAD

**Issue by roseduan** [rosedblabs/rosedb#156]
Slack channel:
https://join.slack.com/t/flowercorp-slack/shared_invite/zt-19oj8ecqb-V02ycMV0BH1~Tn6tfeTz6A

**Comment by roseduan** [comment]
join us!
@gozeloglu @icemint0828 @Roderland @Reid00

**Comment by Yukino831143** [comment]
What is the task of this community and what are the requirements for member?

**Comment by roseduan** [comment]
> What is the task of this community and what are the requirements for member?

You can share your ideas or problems in the community with other rosedb developers and users.
RoseDB is also an open project that anyone can contribute to.
