### ISSUE TITLE
add GetAllKeys

### ISSUE THREAD

**Issue by roseduan** [rosedblabs/rosedb#179]
A new feature: list all stored keys conatain all datastructure types.

Here is my idea:
- add GetKeys command in different data types respectively(`GetStrsKeys, GetListKeys, GetHashKeys`...)
- add GetAllKeys command in `db.go`, retrieve all data types `GetKeys` concurrently

The GetAllKeys method like this: 
`func (db *RoseDB) GetAllKeys(dataTypes... DataType) (map[DataType][][]byte, error)`

**Comment by roseduan** [comment]
I have add a GetStrsKeys method in strs.go

**Comment by Reid00** [comment]
I have added pr https://github.com/flower-corp/rosedb/pull/182
