### ISSUE TITLE
Use function instead of closures

### ISSUE THREAD

**Issue by zll600** [rosedblabs/rosedb#203]
**Is your feature request related to a problem? Please describe.**

The code of these closures is too long, resulting in a large amount of code for this function, and these closures only capture the variable `db`.
![image](https://user-images.githubusercontent.com/71714656/215237048-5e72469e-46ce-4c99-92ba-89e9a8e10763.png)

**Describe the solution you'd like**

Rewrite these closures with functions.

**Additional context**

**Comment by gozeloglu** [comment]
Hi @zll600. You might be right, closures can be converted to functions. What does @roseduan think about it?

**Comment by roseduan** [comment]
Thanks! I am refactoring the project, and I will consider your opinion.
