### ISSUE TITLE
use sync.Pool to optimize db.Put operation

### ISSUE THREAD

**Issue by roseduan** [rosedblabs/rosedb#235]
Now the `db.Put` operation will create a new batch every time, which may cause too much memory allocation.
We can use `sync.Pool` to avoid this.

The goleveldb has done this, see https://github.com/syndtr/goleveldb/blob/master/leveldb/db_write.go#L362

**Comment by Jeremy-Run** [comment]
> Now the `db.Put` operation will create a new batch every time, which may cause too much memory allocation. We can use `sync.Pool` to avoid this.
> 
> The goleveldb has done this, see https://github.com/syndtr/goleveldb/blob/master/leveldb/db_write.go#L362

That's a good idea

**Comment by roseduan** [comment]
Thanks, I have done this in commit https://github.com/rosedblabs/rosedb/commit/02c9953b087844bac17df29a5551cf7611c6cccc

you can add it to lotusdb if you want.
