### ISSUE TITLE
Bug: read lock is never released

### ISSUE THREAD

**Issue by tobehardest** [rosedblabs/rosedb#238]
<img width="709" alt="image" src="https://github.com/rosedblabs/rosedb/assets/88612778/c30472be-479e-48fe-bab1-9078ae7a6942">

If record == nil, the if statement cannot enter, and Rlock will never Runlock, which will cause the wait reader of this lock to increase continuously, and finally when the wait reader == 98, panic

**Comment by roseduan** [comment]
Thanks, I have fixed in https://github.com/rosedblabs/rosedb/commit/bca110f04908a224294646abb20907db4b6e9f57
