### ISSUE TITLE
Should we delete the original file after merge?

### ISSUE THREAD

**Issue by Jeremy-Run** [rosedblabs/rosedb#251]
When I open the db, multiple merges will generate a lot of segment files, code example:
```
func test() {
	options := DefaultOptions
	options.DirPath = "./tmp/"
	db, err := Open(options)
	assert.Nil(t, err)
	defer db.Close()

	for i := 0; i < 10; i++ {
		err := db.Put(utils.GetTestKey(i), utils.RandomValue(128))
		assert.Nil(t, err)
	}

	for i := 0; i < 10; i++ {
		err = db.Merge()
		assert.Nil(t, err)
	}
}
```
![image](https://github.com/rosedblabs/rosedb/assets/43458116/eb4fed3c-21cf-4de9-99d3-42a097811694)

Merge does not delete the source file, which means that the space occupied by the disk has not been reduced. Do we need to replace the source file after the merge?

btw, we have this operation when open db.

**Comment by roseduan** [comment]
The reason why there are some many 0-sized segment files is that every time merge happens, we will open a new segment to accept the new writes.

But in this test, no new writes at all.

I think we can delete the opened segment file if its size is 0 after the merge is done.

**Comment by Jeremy-Run** [comment]
> 

Do you think we need to delete the source files after the merge is done? This will save disk resources, but the index needs to be rebuilt.

**Comment by Jeremy-Run** [comment]
> The reason why there are some many 0-sized segment files is that every time merge happens, we will open a new segment to accept the new writes.
> 
> But in this test, no new writes at all.
> 
> I think we can delete the opened segment file if its size is 0 after the merge is done.

Do you think we need to delete the source files after the merge is done? This will save disk resources, but the index needs to be rebuilt.

**Comment by roseduan** [comment]
Yes, I have thought about this problem before.
I think we can add a parameter called reopenAfterDone in Merge to rebuild the index and delete all source files.

I will add this enhancement in next release if you`d like to contribute, thanks.

BTW, someone create a  PR about watch feature, you can review it.

**Comment by Jeremy-Run** [comment]
Ok, you can assign it to me.
