### ISSUE TITLE
V2.3.1 release plan

### ISSUE THREAD

**Issue by roseduan** [rosedblabs/rosedb#261]
- [x] #263
- [x] #262
* AscendRange()
* DescendRange()
* AscendGreaterOrEqual()
* DescendLessOrEqual()

- [ ] Maybe more...

**Comment by weijiew** [comment]
Have you considered supporting distribution, such as utilizing the raft module in etcd, to provide distributed functionality as an optional choice for users? If feasible, I could implement this aspect of the functionality.

**Comment by roseduan** [comment]
> Have you considered supporting distribution, such as utilizing the raft module in etcd, to provide distributed functionality as an optional choice for users? If feasible, I could implement this aspect of the functionality.

This is a huge work, I think we can have a try, do you have any experience in distributed storage systems?

**Comment by weijiew** [comment]
I think that etcd's Raft implementation is a more mature module and practically the de facto standard for Raft. If it's just a porting effort, it shouldn't be too substantial (though this is just speculation). Of course, if starting from scratch, that would involve a significantly larger amount of work. As a beginner in distributed systems, I've been recently studying the Raft module in tinykv, and I noticed that the Raft module in tinykv is also a port from etcd. Seeing this project not being implemented led me to this idea.

**Comment by weijiew** [comment]
> I think that etcd's Raft implementation is a more mature module and practically the de facto standard for Raft. If it's just a porting effort, it shouldn't be too substantial (though this is just speculation). Of course, if starting from scratch, that would involve a significantly larger amount of work. As a beginner in distributed systems, I've been recently studying the Raft module in tinykv, and I noticed that the Raft module in tinykv is also a port from etcd. Seeing this project not being implemented led me to this idea.

I think that etcd's Raft implementation is a more mature module and practically the de facto standard for Raft. If it's just a porting effort, it shouldn't be too substantial (though this is just speculation). Of course, if starting from scratch, that would involve a significantly larger amount of work. As a beginner in distributed systems, I've been recently studying the Raft module in tinykv, and I noticed that the Raft module in tinykv is also a port from etcd. Seeing this project not being implemented led me to this idea.

**Comment by weijiew** [comment]
> > Have you considered supporting distribution, such as utilizing the raft module in etcd, to provide distributed functionality as an optional choice for users? If feasible, I could implement this aspect of the functionality.
> 
> This is a huge work, I think we can have a try, do you have any experience in distributed storage systems?

I think that etcd's Raft implementation is a more mature module and practically the de facto standard for Raft. If it's just a porting effort, it shouldn't be too substantial (though this is just speculation). Of course, if starting from scratch, that would involve a significantly larger amount of work. As a beginner in distributed systems, I've been recently studying the Raft module in tinykv, and I noticed that the Raft module in tinykv is also a port from etcd. Seeing this project not being implemented led me to this idea.

**Comment by roseduan** [comment]
> 

Ok, I can create a new project for this(like RoseKV or some other names you can suggest)

You can list a complete design plan and split it into different modules, so that other interested people can participate in it.

This can be a long-term work, try to stick with it and don't quit halfway...

If you do this well, I can assign the project to you as a maintainer.

**Comment by weijiew** [comment]
> > > > Have you considered supporting distribution, such as utilizing the raft module in etcd, to provide distributed functionality as an optional choice for users? If feasible, I could implement this aspect of the functionality.你有没有考虑过支持分布式，比如利用etcd中的raft模块，为用户提供分布式功能作为一个可选的选择？如果可行的话，我可以实现这方面的功能。
> > > 
> > > 
> > > This is a huge work, I think we can have a try, do you have any experience in distributed storage systems?这是一个巨大的工作，我想我们可以尝试一下，你有任何分布式存储系统的经验吗？
> > 
> > 
> > I think that etcd's Raft implementation is a more mature module and practically the de facto standard for Raft. If it's just a porting effort, it shouldn't be too substantial (though this is just speculation). Of course, if starting from scratch, that would involve a significantly larger amount of work. As a beginner in distributed systems, I've been recently studying the Raft module in tinykv, and I noticed that the Raft module in tinykv is also a port from etcd. Seeing this project not being implemented led me to this idea.我认为etcd的Raft实现是一个更成熟的模块，实际上是Raft的事实标准。如果这只是一个移植工作，那么它不应该太大（尽管这只是猜测）。当然，如果从头开始，那将涉及大量的工作。作为分布式系统的初学者，我最近一直在研究tinykv中的Raft模块，我注意到tinykv中的Raft模块也是etcd的一个端口。看到这个项目没有实施，我产生了这个想法。
> 
> Ok, I can create a new project for this(like RoseKV or some other names you can suggest)好的，我可以为此创建一个新项目（比如RoseKV或者其他你可以建议的名字）
> 
> You can list a complete design plan and split it into different modules, so that other interested people can participate in it.您可以列出一个完整的设计计划，并将其拆分为不同的模块，以便其他感兴趣的人可以参与其中。
> 
> This can be a long-term work, try to stick with it and don't quit halfway...这可能是一个长期的工作，尽量坚持下去，不要半途而废。
> 
> If you do this well, I can assign the project to you as a maintainer.如果你做得很好，我可以把这个项目分配给你作为维护者。

Let me give it a try and make some local modifications. I'll make progress first, and then I'll follow your suggestions. After all, I'm just a beginner in distributed systems, and I haven't finished writing tinykv yet. 😭 I'm not too confident about it.

**Comment by weijiew** [comment]
> > > > Have you considered supporting distribution, such as utilizing the raft module in etcd, to provide distributed functionality as an optional choice for users? If feasible, I could implement this aspect of the functionality.
> > > 
> > > 
> > > This is a huge work, I think we can have a try, do you have any experience in distributed storage systems?
> > 
> > 
> > I think that etcd's Raft implementation is a more mature module and practically the de facto standard for Raft. If it's just a porting effort, it shouldn't be too substantial (though this is just speculation). Of course, if starting from scratch, that would involve a significantly larger amount of work. As a beginner in distributed systems, I've been recently studying the Raft module in tinykv, and I noticed that the Raft module in tinykv is also a port from etcd. Seeing this project not being implemented led me to this idea.
> 
> Ok, I can create a new project for this(like RoseKV or some other names you can suggest)
> 
> You can list a complete design plan and split it into different modules, so that other interested people can participate in it.
> 
> This can be a long-term work, try to stick with it and don't quit halfway...
> 
> If you do this well, I can assign the project to you as a maintainer.

Let me give it a try and make some local modifications. I'll make progress first, and then I'll follow your suggestions. After all, I'm just a beginner in distributed systems, and I haven't finished writing tinykv yet. 😭 I'm not too confident about it.
