### ISSUE TITLE
Expired Keys Found in AscendKeys/DescendKeys

### ISSUE THREAD

**Issue by taroim** [rosedblabs/rosedb#285]
When iterating through data using AscendKeys/DescendKeys, is it observed that expired keys are still being output?

**Comment by roseduan** [comment]
I rechecked the logic, it does as you said.

If we check the expiration time while iterating, it will have disk seeking, which will slow down the performance.

I can add this if you want. But the iterate performance will be a little slower.

**Comment by taroim** [comment]
You could consider adding an option to determine whether to filter out expired KEYs

**Comment by roseduan** [comment]
> You could consider adding an option to determine whether to filter out expired KEYs

OK Thanks

**Comment by roseduan** [comment]
Added in the latest release, enjoy!
