### ISSUE TITLE
Proposal: keep key and value into memory

### ISSUE THREAD

**Issue by 0x5487** [rosedblabs/rosedb#288]
Scenario: 
When building a low-latency service, people would like to keep all key and values in memory.  This way will reduce one disk IO to fetch value. 

Proposal:
we can create a new option.  For example, the Mode field has two options.  

1. KeyOnly
2. KeyAndValue

```
// Options specifies the options for opening a database.
type Options struct {
    Mode: KeyAndValue
}
```

**Comment by roseduan** [comment]
Thanks, are you already using rosedb in production?
I can add this feature in the next release.

**Comment by 0x5487** [comment]
No, not yet.  we are still investing.

**Comment by roseduan** [comment]
> No, not yet. we are still investigating.

Hello, are you still investigating?
