### ISSUE TITLE
Proposal: raft protocol support

### ISSUE THREAD

**Issue by 0x5487** [rosedblabs/rosedb#290]
Scenario:
As a core service.  It always needs to be high availability.  If one node was down, other nodes needed to take ownership.  

Proposal:
use raft protocol to enhance high availability to avoid one node being down.  Also, need to implement the snapshot feature to work with the raft.

**Comment by roseduan** [comment]
This is a long-term job, and may need a lot of time. 
If this is truly what you want, I can add it to the plan.

**Comment by 0x5487** [comment]
Yep, agree.  That is a long-term job.  I can share feedback on my investing.  

snapshot:
I plan to create a snapshot file of the current state of RoseDB.  There are two ways that have come to my mind at the moment.

idea 1:  copy all the segment files to another directory and log the current time.  After that, create a goroutine to iterate WAL files and compare each record's time.  If the record's created time is greater than the current time, the record needs to be removed.  
However, the records struct doesn't have a created time field at the moment.  Maybe the field can be added later?

idea 2: If WAL were using a sparse file, we can log the actual size when the snapshot function is called.  After that, we can just copy all the segment files and truncate the last active file's size to the actual size.
